name: "Build test development"

on:
    push:
        branches:
            - dev

env:
  CARGO_TERM_COLOR: always

# This workflow will build your tauri app without uploading it anywhere.
# This is useful to test if the build works on different platforms.
# It will run on ubuntu, macos and windows runners.
# It will build for x86_64 and aarch64 on macos runners.

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: 'aarch64-apple-darwin'
          - platform: 'macos-latest'
            args: 'x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: 'x86_64-unknown-linux-gnu'
          - platform: 'windows-latest'
            args: 'x86_64-pc-windows-msvc'

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      
      - name: Install node and pnpm
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install targets
        run : rustup target add wasm32-unknown-unknown ${{ matrix.args }}

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ runner.os }}
          shared-key: ${{ matrix.args}}
          key: build_test_development
          workspaces: './src-tauri -> target'

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm tauri build --no-bundle -v -t ${{ matrix.args }}